create or replace function http.status_text(
  status_code http.status_code
) returns text as $$
  select
    case status_code
      when 100 then 'Continue'
      when 101 then 'Switching Protocols'
      when 103 then 'Early Hints'
      when 200 then 'OK'
      when 201 then 'Created'
      when 202 then 'Accepted'
      when 203 then 'Non-Authoritative Information'
      when 204 then 'No Content'
      when 205 then 'Reset Content'
      when 206 then 'Partial Content'
      when 300 then 'Multiple Choices'
      when 301 then 'Moved Permanently'
      when 302 then 'Found'
      when 303 then 'See Other'
      when 304 then 'Not Modified'
      when 307 then 'Temporary Redirect'
      when 308 then 'Permanent Redirect'
      when 400 then 'Bad Request'
      when 401 then 'Unauthorized'
      when 402 then 'Payment Required'
      when 403 then 'Forbidden'
      when 404 then 'Not Found'
      when 405 then 'Method Not Allowed'
      when 406 then 'Not Acceptable'
      when 407 then 'Proxy Authentication Required'
      when 408 then 'Request Timeout'
      when 409 then 'Conflict'
      when 410 then 'Gone'
      when 411 then 'Length Required'
      when 412 then 'Precondition Failed'
      when 413 then 'Payload Too Large'
      when 414 then 'URI Too Long'
      when 415 then 'Unsupported Media Type'
      when 416 then 'Range Not Satisfiable'
      when 417 then 'Expectation Failed'
      when 418 then E'I\'m a teapot'
      when 422 then 'Unprocessable Entity'
      when 425 then 'Too Early'
      when 426 then 'Upgrade Required'
      when 428 then 'Precondition Required'
      when 429 then 'Too Many Requests'
      when 431 then 'Request Header Fields Too Large'
      when 451 then 'Unavailable For Legal Reasons'
      when 500 then 'Internal Server Error'
      when 501 then 'Not Implemented'
      when 502 then 'Bad Gateway'
      when 503 then 'Service Unavailable'
      when 504 then 'Gateway Timeout'
      when 505 then 'HTTP Version Not Supported'
      when 506 then 'Variant Also Negotiates'
      when 507 then 'Insufficient Storage'
      when 508 then 'Loop Detected'
      when 510 then 'Not Extended'
      when 511 then 'Network Authentication Required'
      else ''
    end;
$$ language sql strict immutable security invoker;
